var docs = {}

/*********** UTILITIES ***********/
// Helper method to observe changes to a DOM element. Used in the getSelection
// and getCurrentParagraph methods, where we watch the element that Kix puts
// the selection into when you press ctrl+C.
docs.observe = function (el, config, callback, observeOnce) {
    observeOnce = (typeof observeOnce !== "undefined") && observeOnce;

    var observer = new MutationObserver(function(mutations) {
        if (observeOnce) {
            observer.disconnect();
        }
        
        callback(mutations);
    });

    observer.observe(el, config);
    return observer;
};

// Helper method to translate keys (including a few special/command keys) to
// keyCodes for use with docs.pressKey(keyCode, ...).
docs.codeFromKey = function(key) {
    const specialKeys = {
        "Backspace": 8,
        "Tab": 9,
        "Enter": 13,
        "Shift": 16,
        "Control": 17,
        "Alt": 18,
        "Escape": 27,
        " ": 32,
        "End": 35,
        "Home": 36,
        "ArrowLeft": 37,
        "ArrowUp": 38,
        "ArrowRight": 39,
        "ArrowDown": 40,
        "Delete": 46,
        "Z": 90,
        "/": 191
    };
    if (key in specialKeys) {
        return specialKeys[key];
    }
    return key.charCodeAt(key);
};

/*********** KEYBOARD INTERACTION ***********/
// texttarget is the underlying text editor that Docs uses for catching keyboard input, etc
docs.texttarget = document.querySelector(".docs-texteventtarget-iframe").contentDocument.querySelector("[contenteditable=\"true\"]")

// You can catch user input in the editor by setting docs.keydown to be your
// handler. Key presses generated by Docs+ will be ignored. You should be able
// to use e.key in all modern browsers.
docs.keydown_ = function (e) {
    if (e.docs_plus_ || !docs.keydown) {
        return;
    }
    return docs.keydown(e);
};
docs.texttarget.addEventListener("keydown", docs.keydown_);

// Simulate a key press.
docs.pressKey = function (keyCode, ctrlKey, shiftKey) {
    var el = document.getElementsByClassName("docs-texteventtarget-iframe")[0];
    el = el.contentDocument;

    var is_command = (keyCode <= 46) || ctrlKey;

    var data = {"keyCode": keyCode, "ctrlKey": ctrlKey, "shiftKey": shiftKey};
    var key_event;
    if (is_command) {
        key_event = new KeyboardEvent("keydown", data);
    } else {
        key_event = new KeyboardEvent("keypress", data);
    }
    key_event.docs_plus_ = true;

    el.dispatchEvent(key_event);
};


// UNUSED AND UNTESTED FUNCTION
// Pastes a block of plaintext into the document. Note that spaces before/after
// @text don't seem to work. Also note that repeated pastes can cause serious
// problems --- please give each paste a few hunderd milliseconds to finish
// before sending another pasteText. See test.js for an example of this.
docs.pasteText = function (text) {
    var el = document.getElementsByClassName("docs-texteventtarget-iframe")[0];
    el = el.contentDocument.querySelector("[contenteditable=true]");

    var data = new DataTransfer();
    data.setData("text/plain", text);
    var paste = new ClipboardEvent("paste", {
        "clipboardData": data,
        "data": text,
        "dataType": "text/plain"
    });
    paste.docs_plus_ = true;

    el.dispatchEvent(paste);
};

docs.userCursor = document.querySelector(".kix-cursor");
docs.cursorCaret = document.querySelector(".kix-cursor-caret");

// Sets the width of the user's insertion point marker. @width should be a
// width value compatible with CSS border-width: @width;
docs.setCursorWidth = function(width) {
    docs.cursorCaret.style.borderWidth = width;
};


docs.fontSizeInput = document.querySelector(".jfk-textinput.goog-toolbar-combo-button-input[aria-label=\"Font size\"]");


// Get the current font size (where the cursor is)
docs.getFontSize = function() {
    return docs.fontSizeInput.value;
}

// Edge case: Your view may scroll up or down a line if you're view is of the cursor at the very top
docs.atStartOfLine = function() {
    // We are going to get the initial Y Coordinate, move one character left, get the y coord (move back), and compare the two
    // If they are different, we are at the start of the line
    let coords = docs.userCursor.style.transform;
    let xIndex = coords.indexOf("px");
    let initialYCoord = coords.slice(xIndex + 4, coords.length - 3);
    docs.pressKey(docs.codeFromKey("ArrowLeft"));
    coords = docs.userCursor.style.transform;
    xIndex = coords.indexOf("px");
    let finalYCoord = coords.slice(xIndex + 4, coords.length - 3);
    docs.pressKey(docs.codeFromKey("ArrowRight")); // Undo our key action

    if (initialYCoord !== finalYCoord) { // Y Coords different --> At start of line
        return true;
    }
    return false; // Not at start of line
}

// Returns an array of booleans representing the cursor's location [atStartOfLine, atEndOfLine, atStartOfFile, atEndOfFile]
// The point of coupling so many functions together is to reduce the number of times we have to move the cursor
// This function moves the cursor 3 times
docs.getCursorLocations = function() {
    let result = [false, false, false, false];
    let initialCoords = docs.userCursor.style.transform;
    let initialXIndex = initialCoords.indexOf("px");
    let initialYCoord = initialCoords.slice(initialXIndex + 4, initialCoords.length - 3);
    docs.pressKey(docs.codeFromKey("ArrowLeft"));
    let newCoords = docs.userCursor.style.transform;
    let newXIndex = newCoords.indexOf("px");
    let newYCoord = newCoords.slice(newXIndex + 4, newCoords.length - 3);
    if (initialCoords === newCoords) {
        // We are the start of the file since going left did nothing
        // This also means we shouldn't ArrowRight, since our ArrowLeft didn't do anything
        result[2] = true;
        result[0] = true;
    }
    else if (initialYCoord !== newYCoord) {
        // We are at the start of a line since our Y (height), changed
        result[0] = true;
        docs.pressKey(docs.codeFromKey("ArrowRight"));

    }
    else {
        docs.pressKey(docs.codeFromKey("ArrowRight"));
    }

    // Now we need to check end of line/end of file
    docs.pressKey(docs.codeFromKey("ArrowRight"));
    newCoords = docs.userCursor.style.transform;
    newXIndex = newCoords.indexOf("px");
    newYCoord = newCoords.slice(newXIndex + 4, newCoords.length - 3);

    if (initialCoords === newCoords) {
        // We are at the end of the file since going right did nothing
        // This also means we shouldn't ArrowLeft, since our ArrowRight didn't do anything
        result[3] = true;
        result[1] = true;
    }
    else if (newYCoord !== initialYCoord) {
        // We are at the end of a line since our Y (height), changed
        result[1] = true;
        docs.pressKey(docs.codeFromKey("ArrowLeft"));
    }
    else {
        docs.pressKey(docs.codeFromKey("ArrowLeft"));
    }

    return result;
}


export { docs }