var docs = {};

docs.isMac = false;
let macPlatforms = ["MacIntel", "MacPPC", "Mac68K", "iPhone", "iPad"];
if (macPlatforms.includes(navigator.platform)) {
	docs.isMac = true;
}

// Helper method to translate keys (including a few special/command keys) to
// keyCodes for use with docs.pressKey(keyCode, ...).
if (!docs.isMac) {
	docs.codeFromKey = function (key) {
		const specialKeys = {
			Backspace: 8,
			Tab: 9,
			Enter: 13,
			Shift: 16,
			Control: 17,
			Escape: 27,
			Space: 32,
			End: 35,
			Home: 36,
			ArrowLeft: 37,
			ArrowUp: 38,
			ArrowRight: 39,
			ArrowDown: 40,
			Delete: 46,
			Z: 90,
			PageUp: 33,
			PageDown: 34,
			f: 70,
			F: 70,
		};
		if (key in specialKeys) {
			return specialKeys[key];
		}
		return key.charCodeAt(key);
	};
} else {
	docs.codeFromKey = function (key) {
		const specialKeys = {
			Backspace: 8,
			Tab: 9,
			Enter: 13,
			Shift: 16,
			Control: 18, // Critical
			Escape: 27,
			End: 35,
			Home: 36,
			ArrowLeft: 37,
			ArrowUp: 38,
			ArrowRight: 39,
			ArrowDown: 40,
			Delete: 46,
			Z: 90,
            V: 86, // Critical
			PageUp: 33,
			PageDown: 34,
			f: 70,
			F: 70,
		};
		if (key in specialKeys) {
			return specialKeys[key];
		}
		return key.charCodeAt(key);
	};
}

/*********** KEYBOARD INTERACTION ***********/
// texttarget is the underlying text editor that Docs uses for catching keyboard input, etc

// We use this for copying text only (basically just for y commands)
docs.contentDocument = document.querySelector(
	".docs-texteventtarget-iframe"
).contentDocument;

// This is very important, and is the place where we direct all of our key events
docs.texttarget = docs.contentDocument.querySelector(
	'[contenteditable="true"]'
);

// You can catch user input in the editor by setting docs.keydown to be your
// handler. Key presses generated by Docs+ will be ignored. You should be able
// to use e.key in all modern browsers.
docs.keydown_ = function (e) {
	if (e.docs_plus_ || !docs.keydown) {
		return;
	}
	return docs.keydown(e);
};
docs.texttarget.addEventListener("keydown", docs.keydown_);

// Simulate a key press.
// keyCode, ctrlKey (or altKey on Mac), shiftKey, commandKey(Mac only)
docs.pressKey = function (keyCode, ctrlKey, shiftKey) {
	var el = document.getElementsByClassName("docs-texteventtarget-iframe")[0];
	el = el.contentDocument;

	let is_command = keyCode <= 46 || ctrlKey;

	let data;
	if (!docs.isMac) {
		data = { keyCode: keyCode, ctrlKey: ctrlKey, shiftKey: shiftKey };
	} else {
		data = { keyCode: keyCode, altKey: ctrlKey, shiftKey: shiftKey };

		// Now we have to check for Mac-Specific modifications that may need to be done
		if (keyCode === docs.codeFromKey("Z") && ctrlKey === true) {
			// Undo
			data = { keyCode: keyCode, metaKey: true };
		} else if (keyCode === docs.codeFromKey("Home") && ctrlKey === true) {
			// Home  (to go up)
			data = {
				keyCode: docs.codeFromKey("ArrowUp"),
				shiftKey: shiftKey,
				metaKey: true,
			};
		} else if (keyCode === docs.codeFromKey("End") && ctrlKey === true) {
			// End (to go down)
			data = {
				keyCode: docs.codeFromKey("ArrowDown"),
				shiftKey: shiftKey,
				metaKey: true,
			};
		} 
		else if (keyCode === docs.codeFromKey("Y") && ctrlKey === true) {
			data = {
				keyCode: keyCode,
				metaKey: true
			}
		}
		else if (keyCode === docs.codeFromKey("f") && ctrlKey === true) {
			// Works for both "F" and "f" since they both have same keycode
			data = {
				keyCode: keyCode,
				metaKey: true
			}
		}
		
		else if (keyCode === docs.codeFromKey("V")) {
            // Paste
			// TODO: Remove this (appears unused in reality)
            data = { keyCode: keyCode, metaKey: true };
		}
	}

	var key_event;
	if (is_command) {
		key_event = new KeyboardEvent("keydown", data);
	} else {
		key_event = new KeyboardEvent("keypress", data);
	}
	key_event.docs_plus_ = true;

	el.dispatchEvent(key_event);
};

docs.pressSpecialKey = function (key) {
	var el = document.getElementsByClassName("docs-texteventtarget-iframe")[0];
	el = el.contentDocument;
	let data = { key: key };
	let isCommand = false;
	switch (key) {
		case "$":
			data.keyCode = 36;
			data.shiftKey = true;
			data.code = "Digit4";
			break;
		case " ":
			data.keyCode = 32;
			data.code = "Space";
			break;
		case "Tab":
			data.keyCode = 9;
			data.code = "Tab";
			isCommand = true;
			break;
		case "#":
			data.keyCode = 35;
			data.shiftKey = true;
			data.code = "Digit3";
			break;
		case "%":
			data.keyCode = 37;
			data.shiftKey = true;
			data.code = "Digit5";
			break;
		case "&":
			data.keyCode = 38;
			data.shiftKey = true;
			data.code = "Digit7";
			break;
		case "*":
			data.keyCode = 42;
			data.shiftKey = true;
			data.code = "Digit8";
			break;
		case "(":
			data.keyCode = 40;
			data.shiftKey = true;
			data.code = "Digit9";
			break;
		case ")":
			data.keyCode = 41;
			data.shiftKey = true;
			data.code = "Digit0";
			break;
		case "+":
			data.keyCode = 43;
			data.shiftKey = true;
			data.code = "Equal";
			break;
		case "-":
			data.keyCode = 45;
			data.code = "Minus";
			break;
		case "!":
			data.keyCode = 33;
			data.shiftKey = true;
			data.code = "Digit1";
			break;
		case ",":
			data.keyCode = 44;
			data.code = "Comma";
			break;
		case ".":
			data.keyCode = 46;
			data.code = "Period";
			break;
		case "'":
			data.keyCode = 39;
			data.code = "Quote";
			break;
		case "\"":
			data.keyCode = 34;
			data.shiftKey = true;
			data.code = "Quote";
			break;
	}

	let key_event;
	if (!isCommand) {
		key_event = new KeyboardEvent("keypress", data);
	}
	else {
		key_event = new KeyboardEvent("keydown", data);
	}
	key_event.docs_plus_ = true;

	el.dispatchEvent(key_event);
}

// Pastes plain text into the document
docs.pasteClipboardPlainText = async function () {
	let data = new DataTransfer();
	data.setData("text/plain", await navigator.clipboard.readText());
	var paste = new ClipboardEvent("paste", {
		clipboardData: data,
		dataType: "text",
	});
	paste.docs_plus_ = true;

	await docs.texttarget.dispatchEvent(paste);
};

docs.userCursor = document.querySelector(".kix-cursor");
docs.cursorCaret = document.querySelector(".kix-cursor-caret");

// Sets the width of the user's insertion point marker. @width should be a
// width value compatible with CSS border-width: @width;
docs.setCursorWidth = function (isRegular) {
	if (isRegular) {
		// For normal mode, regular width cursor
		docs.cursorCaret.style.borderWidth = "2px";
	} else {
		// The cursor width will be 41.5% the size of the cursor
		let cursorWidth = parseFloat(
			docs.cursorCaret.style.height.slice(0, -2) * 0.416
		);
		docs.cursorCaret.style.borderWidth = cursorWidth + "px";
	}
};

docs.fontSizeInput = document.querySelector(
	'.jfk-textinput.goog-toolbar-combo-button-input[aria-label="Font size"]'
);

// Get the current font size (where the cursor is)
docs.getFontSize = function () {
	return docs.fontSizeInput.value;
};

// Edge case: Your view may scroll up or down a line if you're view is of the cursor at the very top
docs.atStartOfLine = function () {
	// We are going to get the initial Y Coordinate, move one character left, get the y coord (move back), and compare the two
	// If they are different, we are at the start of the line
	let coords = docs.userCursor.style.transform;
	let xIndex = coords.indexOf("px");
	let initialYCoord = coords.slice(xIndex + 4, coords.length - 3);
	docs.pressKey(docs.codeFromKey("ArrowLeft"));
	coords = docs.userCursor.style.transform;
	xIndex = coords.indexOf("px");
	let finalYCoord = coords.slice(xIndex + 4, coords.length - 3);
	docs.pressKey(docs.codeFromKey("ArrowRight")); // Undo our key action

	if (initialYCoord !== finalYCoord) {
		// Y Coords different --> At start of line
		return true;
	}
	return false; // Not at start of line
};

// Returns an array of booleans representing the cursor's location [atStartOfLine, atEndOfLine, atStartOfFile, atEndOfFile]
// The point of coupling so many functions together is to reduce the number of times we have to move the cursor
// This function moves the cursor 3 times
// atStartofLine and atEndofLine include multi line statements and will return "true" for them too
// Additionally, once you have highlighted text, this function is completely inaccurate and useless
docs.getCursorLocations = function () {
	let result = [false, false, false, false];
	let initialCoords = docs.userCursor.style.transform;
	let initialXIndex = initialCoords.indexOf("px");
	let initialYCoord = initialCoords.slice(
		initialXIndex + 4,
		initialCoords.length - 3
	);
	docs.pressKey(docs.codeFromKey("ArrowLeft"));
	let newCoords = docs.userCursor.style.transform;
	let newXIndex = newCoords.indexOf("px");
	let newYCoord = newCoords.slice(newXIndex + 4, newCoords.length - 3);
	if (initialCoords === newCoords) {
		// We are the start of the file since going left did nothing
		// This also means we shouldn't ArrowRight, since our ArrowLeft didn't do anything
		result[2] = true;
		result[0] = true;
	} else if (initialYCoord !== newYCoord) {
		// We are at the start of a line since our Y (height), changed
		result[0] = true;
		docs.pressKey(docs.codeFromKey("ArrowRight"));
	} else {
		docs.pressKey(docs.codeFromKey("ArrowRight"));
	}

	// Now we need to check end of line/end of file
	docs.pressKey(docs.codeFromKey("ArrowRight"));
	newCoords = docs.userCursor.style.transform;
	newXIndex = newCoords.indexOf("px");
	newYCoord = newCoords.slice(newXIndex + 4, newCoords.length - 3);

	if (initialCoords === newCoords) {
		// We are at the end of the file since going right did nothing
		// This also means we shouldn't ArrowLeft, since our ArrowRight didn't do anything
		result[3] = true;
		result[1] = true;
	} else if (newYCoord !== initialYCoord) {
		// We are at the end of a line since our Y (height), changed
		result[1] = true;
		docs.pressKey(docs.codeFromKey("ArrowLeft"));
	} else {
		docs.pressKey(docs.codeFromKey("ArrowLeft"));
	}

	return result;
};

// Get the y coordinate of the cursor
docs.getYCoord = function () {
	let coords = docs.userCursor.style.transform;
	let xIndex = coords.indexOf("px");
	let yCoord = coords.slice(xIndex + 4, coords.length - 3);
	return parseInt(yCoord);
}

// Get the x and y coordinates of the cursor
docs.getCoords = function () {
	let coords = docs.userCursor.style.transform;
	let xIndex = coords.indexOf("px");
	let xCoord = coords.slice(10, xIndex);
	let yCoord = coords.slice(xIndex + 4, coords.length - 3);
	return [parseInt(xCoord), parseInt(yCoord)];
}


export { docs };
